//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinario.TO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbVeterinariaEntities : DbContext
    {
        public dbVeterinariaEntities()
            : base("name=dbVeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Animal> Animal { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Consulta> Consulta { get; set; }
        public DbSet<Raca> Raca { get; set; }
        public DbSet<Telefone> Telefone { get; set; }
        public DbSet<TelefoneVeterianrio> TelefoneVeterianrio { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<Veterinario> Veterinario { get; set; }
    }
}
